/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *	   Sam Padgett	       - initial API and implementation
 *     Michael Fiedler     - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/


package se.kth.md.it.bcm.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import javax.ws.rs.core.UriBuilder;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import se.kth.md.it.bcm.servlet.ServletListener; 
import se.kth.md.it.bcm.BugzillaAdaptorConstants;
import se.kth.md.it.bcm.resources.Person;	
import se.kth.md.it.bcm.resources.Person;	
import se.kth.md.it.bcm.resources.Type;	

// Start of user code imports
// End of user code

@OslcNamespace(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE)
@OslcName(BugzillaAdaptorConstants.CHANGEREQUEST) 
@OslcResourceShape(title = "ChangeRequest Resource Shape", describes = BugzillaAdaptorConstants.TYPE_CHANGEREQUEST)
public class ChangeRequest
	extends AbstractResource
	implements IChangeRequest
{

private HashSet<Link> affectedByDefect = new HashSet<Link>();  
private HashSet<Link> affectsPlanItem = new HashSet<Link>();  
private HashSet<Link> affectsRequirement = new HashSet<Link>();  
private HashSet<Link> affectsTestResult = new HashSet<Link>();  
private HashSet<Link> blocksTestExecutionRecord = new HashSet<Link>();  
private HashSet<Person> contributor = new HashSet<Person>();  
private HashSet<Person> creator = new HashSet<Person>();  
private HashSet<Type> dctermsType = new HashSet<Type>();  
private HashSet<Link> implementsRequirement = new HashSet<Link>();  
private HashSet<Link> relatedChangeRequest = new HashSet<Link>();  
private HashSet<Link> relatedTestCase = new HashSet<Link>();  
private HashSet<Link> relatedTestExecutionRecord = new HashSet<Link>();  
private HashSet<Link> relatedTestPlan = new HashSet<Link>();  
private HashSet<Link> relatedTestScript = new HashSet<Link>();  
private HashSet<String> subject = new HashSet<String>();  
private HashSet<Link> testedByTestCase = new HashSet<Link>();  
private HashSet<Link> tracksChangeSet = new HashSet<Link>();  
private HashSet<Link> tracksRequirement = new HashSet<Link>();  
private HashSet<URI> rdfType = new HashSet<URI>();  
private Boolean approved;  
private Boolean closed;  
private Date closeDate;  
private Date created;  
private String description;  
private Link discussedBy = new Link();  
private Boolean fixed;  
private String identifier;  
private Boolean inprogress;  
private Link instanceShape = new Link();  
private Date modified;  
private Boolean reviewed;  
private URI serviceProvider;  
private String shortTitle;  
private String status;  
private String title;  
private Boolean verified;  

public ChangeRequest()
       throws URISyntaxException
{
    super();

	// Start of user code constructor1
	// End of user code
}

public ChangeRequest(final URI about)
       throws URISyntaxException
{
    super(about);

	// Start of user code constructor2
	// End of user code
}

public ChangeRequest(final String serviceProviderId, final String changeRequestId)
       throws URISyntaxException
{
	this (constructURI(serviceProviderId, changeRequestId));
	// Start of user code constructor3
	// End of user code
}

public static URI constructURI(final String serviceProviderId, final String changeRequestId)
{
    String basePath = ServletListener.getServicesBase();
    Map<String, Object> pathParameters = new HashMap<String, Object>();
    pathParameters.put("serviceProviderId", serviceProviderId);

    pathParameters.put("changeRequestId", changeRequestId);
    String instanceURI = "serviceProviders/{serviceProviderId}/changeRequests/{changeRequestId}";
  
    final UriBuilder builder = UriBuilder.fromUri(basePath);
    return builder.path(instanceURI).buildFromMap(pathParameters);
}

public static Link constructLink(final String serviceProviderId, final String changeRequestId , final String label)
{
	return new Link(constructURI(serviceProviderId, changeRequestId), label);
}

public static Link constructLink(final String serviceProviderId, final String changeRequestId)
{
	return new Link(constructURI(serviceProviderId, changeRequestId));
}

public String toString()
{
	return toString(false);
}

public String toString(boolean asLocalResource)
{
		String result = "";
		// Start of user code toString_init
		// End of user code

		if (asLocalResource) {
			result = result + "{a Local ChangeRequest Resource} - update ChangeRequest.toString() to present resource as desired.";
			// Start of user code toString_bodyForLocalResource
			// End of user code
		}
		else {
			result = getAbout().toString();
		}

		// Start of user code toString_finalize
		// End of user code

		return result;
}

public String toHtml()
{
	return toHtml(false);
}

public String toHtml(boolean asLocalResource)
{
		String result = "";
		// Start of user code toHtml_init
		// End of user code

		if (asLocalResource) {
			result = toString(true);
			// Start of user code toHtml_bodyForLocalResource
			// End of user code
		}
		else {
			result = "<a href=\"" + getAbout() + "\">" + toString() + "</a>";
		}

		// Start of user code toHtml_finalize
		// End of user code

		return result;
}

    public void addAffectedByDefect(final Link affectedByDefect )
    {
        this.affectedByDefect.add(affectedByDefect);
    }
    public void addAffectsPlanItem(final Link affectsPlanItem )
    {
        this.affectsPlanItem.add(affectsPlanItem);
    }
    public void addAffectsRequirement(final Link affectsRequirement )
    {
        this.affectsRequirement.add(affectsRequirement);
    }
    public void addAffectsTestResult(final Link affectsTestResult )
    {
        this.affectsTestResult.add(affectsTestResult);
    }
    public void addBlocksTestExecutionRecord(final Link blocksTestExecutionRecord )
    {
        this.blocksTestExecutionRecord.add(blocksTestExecutionRecord);
    }
    public void addContributor(final Person contributor )
    {
        this.contributor.add(contributor);
    }
    public void addCreator(final Person creator )
    {
        this.creator.add(creator);
    }
    public void addType(final Type type )
    {
        this.dctermsType.add(type);
    }
    public void addImplementsRequirement(final Link implementsRequirement )
    {
        this.implementsRequirement.add(implementsRequirement);
    }
    public void addRelatedChangeRequest(final Link relatedChangeRequest )
    {
        this.relatedChangeRequest.add(relatedChangeRequest);
    }
    public void addRelatedTestCase(final Link relatedTestCase )
    {
        this.relatedTestCase.add(relatedTestCase);
    }
    public void addRelatedTestExecutionRecord(final Link relatedTestExecutionRecord )
    {
        this.relatedTestExecutionRecord.add(relatedTestExecutionRecord);
    }
    public void addRelatedTestPlan(final Link relatedTestPlan )
    {
        this.relatedTestPlan.add(relatedTestPlan);
    }
    public void addRelatedTestScript(final Link relatedTestScript )
    {
        this.relatedTestScript.add(relatedTestScript);
    }
    public void addSubject(final String subject )
    {
        this.subject.add(subject);
    }
    public void addTestedByTestCase(final Link testedByTestCase )
    {
        this.testedByTestCase.add(testedByTestCase);
    }
    public void addTracksChangeSet(final Link tracksChangeSet )
    {
        this.tracksChangeSet.add(tracksChangeSet);
    }
    public void addTracksRequirement(final Link tracksRequirement )
    {
        this.tracksRequirement.add(tracksRequirement);
    }
    public void addType(final URI type )
    {
        this.rdfType.add(type);
    }

   	@OslcName("affectedByDefect")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "affectedByDefect")
	@OslcDescription("Change request is affected by a reported defect. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getAffectedByDefect()
    {
        return affectedByDefect;
    }

   	@OslcName("affectsPlanItem")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "affectsPlanItem")
	@OslcDescription("Change request affects a plan item. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getAffectsPlanItem()
    {
        return affectsPlanItem;
    }

   	@OslcName("affectsRequirement")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "affectsRequirement")
	@OslcDescription("Change request affecting a Requirement. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getAffectsRequirement()
    {
        return affectsRequirement;
    }

   	@OslcName("affectsTestResult")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "affectsTestResult")
	@OslcDescription("Associated QM resource that is affected by this Change Request. It is likely that the target resource will be an oslc_qm:TestResult but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getAffectsTestResult()
    {
        return affectsTestResult;
    }

   	@OslcName("blocksTestExecutionRecord")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "blocksTestExecutionRecord")
	@OslcDescription("Associated QM resource that is blocked by this Change Request. It is likely that the target resource will be an oslc_qm:TestExecutionRecord but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getBlocksTestExecutionRecord()
    {
        return blocksTestExecutionRecord;
    }

   	@OslcName("contributor")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "contributor")
	@OslcDescription("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case. ")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	
	@OslcRange(BugzillaAdaptorConstants.TYPE_PERSON)
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Person> getContributor()
    {
        return contributor;
    }

   	@OslcName("creator")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "creator")
	@OslcDescription("Creator or creators of resource (reference: Dublin Core). It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	
	@OslcRange(BugzillaAdaptorConstants.TYPE_PERSON)
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Person> getCreator()
    {
        return creator;
    }

   	@OslcName("type")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "type")
	@OslcDescription("A short string representation for the type, example 'Defect'.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	
	@OslcRange(BugzillaAdaptorConstants.TYPE_TYPE)
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Type> getDctermsType()
    {
        return dctermsType;
    }

   	@OslcName("implementsRequirement")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "implementsRequirement")
	@OslcDescription("Implements associated Requirement. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getImplementsRequirement()
    {
        return implementsRequirement;
    }

   	@OslcName("relatedChangeRequest")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "relatedChangeRequest")
	@OslcDescription("This relationship is loosely coupled and has no specific meaning. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getRelatedChangeRequest()
    {
        return relatedChangeRequest;
    }

   	@OslcName("relatedTestCase")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "relatedTestCase")
	@OslcDescription("Related QM test case resource. It is likely that the target resource will be an oslc_qm:TestCase but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getRelatedTestCase()
    {
        return relatedTestCase;
    }

   	@OslcName("relatedTestExecutionRecord")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "relatedTestExecutionRecord")
	@OslcDescription("Related to a QM test execution resource. It is likely that the target resource will be an oslc_qm:TestExecutionRecord but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getRelatedTestExecutionRecord()
    {
        return relatedTestExecutionRecord;
    }

   	@OslcName("relatedTestPlan")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "relatedTestPlan")
	@OslcDescription("Related QM test plan resource. It is likely that the target resource will be an oslc_qm:TestPlan but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getRelatedTestPlan()
    {
        return relatedTestPlan;
    }

   	@OslcName("relatedTestScript")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "relatedTestScript")
	@OslcDescription("Related QM test script resource. It is likely that the target resource will be an oslc_qm:TestScript but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getRelatedTestScript()
    {
        return relatedTestScript;
    }

   	@OslcName("subject")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "subject")
	@OslcDescription("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.String)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<String> getSubject()
    {
        return subject;
    }

   	@OslcName("testedByTestCase")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "testedByTestCase")
	@OslcDescription("Test case by which this change request is tested. It is likely that the target resource will be an oslc_qm:TestCase but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getTestedByTestCase()
    {
        return testedByTestCase;
    }

   	@OslcName("tracksChangeSet")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "tracksChangeSet")
	@OslcDescription("Tracks SCM change set resource. It is likely that the target resource will be an oslc_scm:ChangeSet but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getTracksChangeSet()
    {
        return tracksChangeSet;
    }

   	@OslcName("tracksRequirement")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "tracksRequirement")
	@OslcDescription("Tracks the associated Requirement or Requirement ChangeSet resources. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Link> getTracksRequirement()
    {
        return tracksRequirement;
    }

   	@OslcName("type")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.RDF_NAMSPACE + "type")
	@OslcDescription("The resource type URIs.")
	@OslcOccurs(Occurs.ZeroOrMany)
	
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<URI> getRdfType()
    {
        return rdfType;
    }

   	@OslcName("approved")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "approved")
	@OslcDescription("Whether or not the Change Request has been approved.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isApproved()
    {
        return approved;
    }

   	@OslcName("closed")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "closed")
	@OslcDescription("Whether or not the Change Request is completely done, no further fixes or fix verification is needed.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isClosed()
    {
        return closed;
    }

   	@OslcName("closeDate")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "closeDate")
	@OslcDescription("The date at which no further activity or work is intended to be conducted.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.DateTime)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Date getCloseDate()
    {
        return closeDate;
    }

   	@OslcName("created")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "created")
	@OslcDescription("Timestamp of resource creation")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.DateTime)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Date getCreated()
    {
        return created;
    }

   	@OslcName("description")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "description")
	@OslcDescription("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element. ")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.XMLLiteral)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getDescription()
    {
        return description;
    }

   	@OslcName("discussedBy")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.OSLC_CORE_NAMSPACE + "discussedBy")
	@OslcDescription("A series of notes and comments about this resource.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public Link getDiscussedBy()
    {
        return discussedBy;
    }

   	@OslcName("fixed")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "fixed")
	@OslcDescription("Whether or not the Change Request has been fixed.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isFixed()
    {
        return fixed;
    }

   	@OslcName("identifier")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "identifier")
	@OslcDescription("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
	@OslcOccurs(Occurs.ExactlyOne)
	@OslcValueType(ValueType.String)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public String getIdentifier()
    {
        return identifier;
    }

   	@OslcName("inprogress")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "inprogress")
	@OslcDescription("Whether or not the Change Request in a state indicating that active work is occurring. If oslc_cm:inprogress is true, then oslc_cm:fixed and oslc_cm:closed must also be false")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isInprogress()
    {
        return inprogress;
    }

   	@OslcName("instanceShape")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.OSLC_CORE_NAMSPACE + "instanceShape")
	@OslcDescription("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Resource)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public Link getInstanceShape()
    {
        return instanceShape;
    }

   	@OslcName("modified")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "modified")
	@OslcDescription("Timestamp last latest resource modification")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.DateTime)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Date getModified()
    {
        return modified;
    }

   	@OslcName("reviewed")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "reviewed")
	@OslcDescription("Whether or not the Change Request has been reviewed.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isReviewed()
    {
        return reviewed;
    }

   	@OslcName("serviceProvider")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.OSLC_CORE_NAMSPACE + "serviceProvider")
	@OslcDescription("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property. ")
	@OslcOccurs(Occurs.ExactlyOne)
	
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public URI getServiceProvider()
    {
        return serviceProvider;
    }

   	@OslcName("shortTitle")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.OSLC_CORE_NAMSPACE + "shortTitle")
	@OslcDescription("Shorter form of dcterms:title for the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.XMLLiteral)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getShortTitle()
    {
        return shortTitle;
    }

   	@OslcName("status")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "status")
	@OslcDescription("Used to indicate the status of the change request based on values defined by the service provider. Most often a read-only property. Some possible values may include: 'Submitted', 'Done', 'InProgress', etc.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.String)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getStatus()
    {
        return status;
    }

   	@OslcName("title")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.DUBLIN_CORE_NAMSPACE + "title")
	@OslcDescription("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element. ")
	@OslcOccurs(Occurs.ExactlyOne)
	@OslcValueType(ValueType.XMLLiteral)
	
	
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getTitle()
    {
        return title;
    }

   	@OslcName("verified")
   	@OslcPropertyDefinition(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_NAMSPACE + "verified")
	@OslcDescription("Whether or not the resolution or fix of the Change Request has been verified.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Boolean)
	
	
	@OslcReadOnly(true)
	@OslcTitle("")
    public Boolean isVerified()
    {
        return verified;
    }


    public void setAffectedByDefect(final HashSet<Link> affectedByDefect )
    {
        this.affectedByDefect.clear();
        if (affectedByDefect != null)
        {
            this.affectedByDefect.addAll(affectedByDefect);
        }

    }
    public void setAffectsPlanItem(final HashSet<Link> affectsPlanItem )
    {
        this.affectsPlanItem.clear();
        if (affectsPlanItem != null)
        {
            this.affectsPlanItem.addAll(affectsPlanItem);
        }

    }
    public void setAffectsRequirement(final HashSet<Link> affectsRequirement )
    {
        this.affectsRequirement.clear();
        if (affectsRequirement != null)
        {
            this.affectsRequirement.addAll(affectsRequirement);
        }

    }
    public void setAffectsTestResult(final HashSet<Link> affectsTestResult )
    {
        this.affectsTestResult.clear();
        if (affectsTestResult != null)
        {
            this.affectsTestResult.addAll(affectsTestResult);
        }

    }
    public void setBlocksTestExecutionRecord(final HashSet<Link> blocksTestExecutionRecord )
    {
        this.blocksTestExecutionRecord.clear();
        if (blocksTestExecutionRecord != null)
        {
            this.blocksTestExecutionRecord.addAll(blocksTestExecutionRecord);
        }

    }
    public void setContributor(final HashSet<Person> contributor )
    {
        this.contributor.clear();
        if (contributor != null)
        {
            this.contributor.addAll(contributor);
        }

    }
    public void setCreator(final HashSet<Person> creator )
    {
        this.creator.clear();
        if (creator != null)
        {
            this.creator.addAll(creator);
        }

    }
    public void setDctermsType(final HashSet<Type> type )
    {
        this.dctermsType.clear();
        if (type != null)
        {
            this.dctermsType.addAll(type);
        }

    }
    public void setImplementsRequirement(final HashSet<Link> implementsRequirement )
    {
        this.implementsRequirement.clear();
        if (implementsRequirement != null)
        {
            this.implementsRequirement.addAll(implementsRequirement);
        }

    }
    public void setRelatedChangeRequest(final HashSet<Link> relatedChangeRequest )
    {
        this.relatedChangeRequest.clear();
        if (relatedChangeRequest != null)
        {
            this.relatedChangeRequest.addAll(relatedChangeRequest);
        }

    }
    public void setRelatedTestCase(final HashSet<Link> relatedTestCase )
    {
        this.relatedTestCase.clear();
        if (relatedTestCase != null)
        {
            this.relatedTestCase.addAll(relatedTestCase);
        }

    }
    public void setRelatedTestExecutionRecord(final HashSet<Link> relatedTestExecutionRecord )
    {
        this.relatedTestExecutionRecord.clear();
        if (relatedTestExecutionRecord != null)
        {
            this.relatedTestExecutionRecord.addAll(relatedTestExecutionRecord);
        }

    }
    public void setRelatedTestPlan(final HashSet<Link> relatedTestPlan )
    {
        this.relatedTestPlan.clear();
        if (relatedTestPlan != null)
        {
            this.relatedTestPlan.addAll(relatedTestPlan);
        }

    }
    public void setRelatedTestScript(final HashSet<Link> relatedTestScript )
    {
        this.relatedTestScript.clear();
        if (relatedTestScript != null)
        {
            this.relatedTestScript.addAll(relatedTestScript);
        }

    }
    public void setSubject(final HashSet<String> subject )
    {
        this.subject.clear();
        if (subject != null)
        {
            this.subject.addAll(subject);
        }

    }
    public void setTestedByTestCase(final HashSet<Link> testedByTestCase )
    {
        this.testedByTestCase.clear();
        if (testedByTestCase != null)
        {
            this.testedByTestCase.addAll(testedByTestCase);
        }

    }
    public void setTracksChangeSet(final HashSet<Link> tracksChangeSet )
    {
        this.tracksChangeSet.clear();
        if (tracksChangeSet != null)
        {
            this.tracksChangeSet.addAll(tracksChangeSet);
        }

    }
    public void setTracksRequirement(final HashSet<Link> tracksRequirement )
    {
        this.tracksRequirement.clear();
        if (tracksRequirement != null)
        {
            this.tracksRequirement.addAll(tracksRequirement);
        }

    }
    public void setRdfType(final HashSet<URI> type )
    {
        this.rdfType.clear();
        if (type != null)
        {
            this.rdfType.addAll(type);
        }

    }
    public void setApproved(final Boolean approved )
    {
        this.approved = approved;
    }
    public void setClosed(final Boolean closed )
    {
        this.closed = closed;
    }
    public void setCloseDate(final Date closeDate )
    {
        this.closeDate = closeDate;
    }
    public void setCreated(final Date created )
    {
        this.created = created;
    }
    public void setDescription(final String description )
    {
        this.description = description;
    }
    public void setDiscussedBy(final Link discussedBy )
    {
        this.discussedBy = discussedBy;
    }
    public void setFixed(final Boolean fixed )
    {
        this.fixed = fixed;
    }
    public void setIdentifier(final String identifier )
    {
        this.identifier = identifier;
    }
    public void setInprogress(final Boolean inprogress )
    {
        this.inprogress = inprogress;
    }
    public void setInstanceShape(final Link instanceShape )
    {
        this.instanceShape = instanceShape;
    }
    public void setModified(final Date modified )
    {
        this.modified = modified;
    }
    public void setReviewed(final Boolean reviewed )
    {
        this.reviewed = reviewed;
    }
    public void setServiceProvider(final URI serviceProvider )
    {
        this.serviceProvider = serviceProvider;
    }
    public void setShortTitle(final String shortTitle )
    {
        this.shortTitle = shortTitle;
    }
    public void setStatus(final String status )
    {
        this.status = status;
    }
    public void setTitle(final String title )
    {
        this.title = title;
    }
    public void setVerified(final Boolean verified )
    {
        this.verified = verified;
    }

    static public String affectedByDefectToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code affectedByDefectasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"affectedByDefect\">affectedByDefect: </LABEL>";

		// Start of user code affectedByDefectasHtmlForCreation_mid
		// End of user code


		// Start of user code affectedByDefectasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String affectsPlanItemToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code affectsPlanItemasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"affectsPlanItem\">affectsPlanItem: </LABEL>";

		// Start of user code affectsPlanItemasHtmlForCreation_mid
		// End of user code


		// Start of user code affectsPlanItemasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String affectsRequirementToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code affectsRequirementasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"affectsRequirement\">affectsRequirement: </LABEL>";

		// Start of user code affectsRequirementasHtmlForCreation_mid
		// End of user code


		// Start of user code affectsRequirementasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String affectsTestResultToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code affectsTestResultasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"affectsTestResult\">affectsTestResult: </LABEL>";

		// Start of user code affectsTestResultasHtmlForCreation_mid
		// End of user code


		// Start of user code affectsTestResultasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String blocksTestExecutionRecordToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code blocksTestExecutionRecordasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"blocksTestExecutionRecord\">blocksTestExecutionRecord: </LABEL>";

		// Start of user code blocksTestExecutionRecordasHtmlForCreation_mid
		// End of user code


		// Start of user code blocksTestExecutionRecordasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String contributorToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code contributorasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"contributor\">contributor: </LABEL>";

		// Start of user code contributorasHtmlForCreation_mid
		// End of user code


		// Start of user code contributorasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String creatorToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code creatorasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"creator\">creator: </LABEL>";

		// Start of user code creatorasHtmlForCreation_mid
		// End of user code


		// Start of user code creatorasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String dctermsTypeToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code dctermsTypeasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"type\">type: </LABEL>";

		// Start of user code dctermsTypeasHtmlForCreation_mid
		// End of user code


		// Start of user code dctermsTypeasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String implementsRequirementToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code implementsRequirementasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"implementsRequirement\">implementsRequirement: </LABEL>";

		// Start of user code implementsRequirementasHtmlForCreation_mid
		// End of user code


		// Start of user code implementsRequirementasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String relatedChangeRequestToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code relatedChangeRequestasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"relatedChangeRequest\">relatedChangeRequest: </LABEL>";

		// Start of user code relatedChangeRequestasHtmlForCreation_mid
		// End of user code


		// Start of user code relatedChangeRequestasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String relatedTestCaseToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code relatedTestCaseasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"relatedTestCase\">relatedTestCase: </LABEL>";

		// Start of user code relatedTestCaseasHtmlForCreation_mid
		// End of user code


		// Start of user code relatedTestCaseasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String relatedTestExecutionRecordToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code relatedTestExecutionRecordasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"relatedTestExecutionRecord\">relatedTestExecutionRecord: </LABEL>";

		// Start of user code relatedTestExecutionRecordasHtmlForCreation_mid
		// End of user code


		// Start of user code relatedTestExecutionRecordasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String relatedTestPlanToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code relatedTestPlanasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"relatedTestPlan\">relatedTestPlan: </LABEL>";

		// Start of user code relatedTestPlanasHtmlForCreation_mid
		// End of user code


		// Start of user code relatedTestPlanasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String relatedTestScriptToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code relatedTestScriptasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"relatedTestScript\">relatedTestScript: </LABEL>";

		// Start of user code relatedTestScriptasHtmlForCreation_mid
		// End of user code


		// Start of user code relatedTestScriptasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String subjectToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code subjectasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"subject\">subject: </LABEL>";

		// Start of user code subjectasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"subject\" type=\"text\" style=\"width: 400px\" id=\"subject\" >";

		// Start of user code subjectasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String testedByTestCaseToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code testedByTestCaseasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"testedByTestCase\">testedByTestCase: </LABEL>";

		// Start of user code testedByTestCaseasHtmlForCreation_mid
		// End of user code


		// Start of user code testedByTestCaseasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String tracksChangeSetToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code tracksChangeSetasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"tracksChangeSet\">tracksChangeSet: </LABEL>";

		// Start of user code tracksChangeSetasHtmlForCreation_mid
		// End of user code


		// Start of user code tracksChangeSetasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String tracksRequirementToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code tracksRequirementasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"tracksRequirement\">tracksRequirement: </LABEL>";

		// Start of user code tracksRequirementasHtmlForCreation_mid
		// End of user code


		// Start of user code tracksRequirementasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String rdfTypeToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code rdfTypeasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"type\">type: </LABEL>";

		// Start of user code rdfTypeasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"type\" type=\"text\" style=\"width: 400px\" id=\"type\" >";

		// Start of user code rdfTypeasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String approvedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code approvedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"approved\">approved: </LABEL>";

		// Start of user code approvedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"approved\" type=\"radio\" value=\"true\">True<br><input name=\"approved\" type=\"radio\" value=\"false\">False";

		// Start of user code approvedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String closedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code closedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"closed\">closed: </LABEL>";

		// Start of user code closedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"closed\" type=\"radio\" value=\"true\">True<br><input name=\"closed\" type=\"radio\" value=\"false\">False";

		// Start of user code closedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String closeDateToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code closeDateasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"closeDate\">closeDate: </LABEL>";

		// Start of user code closeDateasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"closeDate\" type=\"text\" style=\"width: 400px\" id=\"closeDate\" >";

		// Start of user code closeDateasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String createdToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code createdasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"created\">created: </LABEL>";

		// Start of user code createdasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"created\" type=\"text\" style=\"width: 400px\" id=\"created\" >";

		// Start of user code createdasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String descriptionToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code descriptionasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"description\">description: </LABEL>";

		// Start of user code descriptionasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"description\" type=\"text\" style=\"width: 400px\" id=\"description\" >";

		// Start of user code descriptionasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String discussedByToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code discussedByasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"discussedBy\">discussedBy: </LABEL>";

		// Start of user code discussedByasHtmlForCreation_mid
		// End of user code


		// Start of user code discussedByasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String fixedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code fixedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"fixed\">fixed: </LABEL>";

		// Start of user code fixedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"fixed\" type=\"radio\" value=\"true\">True<br><input name=\"fixed\" type=\"radio\" value=\"false\">False";

		// Start of user code fixedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String identifierToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code identifierasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"identifier\">identifier: </LABEL>";

		// Start of user code identifierasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"identifier\" type=\"text\" style=\"width: 400px\" id=\"identifier\" >";

		// Start of user code identifierasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String inprogressToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code inprogressasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"inprogress\">inprogress: </LABEL>";

		// Start of user code inprogressasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"inprogress\" type=\"radio\" value=\"true\">True<br><input name=\"inprogress\" type=\"radio\" value=\"false\">False";

		// Start of user code inprogressasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String instanceShapeToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code instanceShapeasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"instanceShape\">instanceShape: </LABEL>";

		// Start of user code instanceShapeasHtmlForCreation_mid
		// End of user code


		// Start of user code instanceShapeasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String modifiedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code modifiedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"modified\">modified: </LABEL>";

		// Start of user code modifiedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"modified\" type=\"text\" style=\"width: 400px\" id=\"modified\" >";

		// Start of user code modifiedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String reviewedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code reviewedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"reviewed\">reviewed: </LABEL>";

		// Start of user code reviewedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"reviewed\" type=\"radio\" value=\"true\">True<br><input name=\"reviewed\" type=\"radio\" value=\"false\">False";

		// Start of user code reviewedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String serviceProviderToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code serviceProviderasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"serviceProvider\">serviceProvider: </LABEL>";

		// Start of user code serviceProviderasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"serviceProvider\" type=\"text\" style=\"width: 400px\" id=\"serviceProvider\" >";

		// Start of user code serviceProviderasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String shortTitleToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code shortTitleasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"shortTitle\">shortTitle: </LABEL>";

		// Start of user code shortTitleasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"shortTitle\" type=\"text\" style=\"width: 400px\" id=\"shortTitle\" >";

		// Start of user code shortTitleasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String statusToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code statusasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"status\">status: </LABEL>";

		// Start of user code statusasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"status\" type=\"text\" style=\"width: 400px\" id=\"status\" >";

		// Start of user code statusasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String titleToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code titleasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"title\">title: </LABEL>";

		// Start of user code titleasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"title\" type=\"text\" style=\"width: 400px\" id=\"title\" >";

		// Start of user code titleasHtmlForCreation_finalize
		// End of user code

		return s; 
    }
    static public String verifiedToHtmlForCreation (final HttpServletRequest httpServletRequest, final String serviceProviderId)
    {
		String s = "";

		// Start of user code verifiedasHtmlForCreation_init
		// End of user code

		s = s + "<label for=\"verified\">verified: </LABEL>";

		// Start of user code verifiedasHtmlForCreation_mid
		// End of user code

				s= s + "<input name=\"verified\" type=\"radio\" value=\"true\">True<br><input name=\"verified\" type=\"radio\" value=\"false\">False";

		// Start of user code verifiedasHtmlForCreation_finalize
		// End of user code

		return s; 
    }

    public String affectedByDefectToHtml()
    {
		String s = "";

		// Start of user code affectedByDefecttoHtml_init
		// End of user code

		s = s + "<label for=\"affectedByDefect\"><strong>affectedByDefect</strong>: </LABEL>";

		// Start of user code affectedByDefecttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = affectedByDefect.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code affectedByDefecttoHtml_finalize
		// End of user code

		return s; 
    }
    public String affectsPlanItemToHtml()
    {
		String s = "";

		// Start of user code affectsPlanItemtoHtml_init
		// End of user code

		s = s + "<label for=\"affectsPlanItem\"><strong>affectsPlanItem</strong>: </LABEL>";

		// Start of user code affectsPlanItemtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = affectsPlanItem.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code affectsPlanItemtoHtml_finalize
		// End of user code

		return s; 
    }
    public String affectsRequirementToHtml()
    {
		String s = "";

		// Start of user code affectsRequirementtoHtml_init
		// End of user code

		s = s + "<label for=\"affectsRequirement\"><strong>affectsRequirement</strong>: </LABEL>";

		// Start of user code affectsRequirementtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = affectsRequirement.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code affectsRequirementtoHtml_finalize
		// End of user code

		return s; 
    }
    public String affectsTestResultToHtml()
    {
		String s = "";

		// Start of user code affectsTestResulttoHtml_init
		// End of user code

		s = s + "<label for=\"affectsTestResult\"><strong>affectsTestResult</strong>: </LABEL>";

		// Start of user code affectsTestResulttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = affectsTestResult.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code affectsTestResulttoHtml_finalize
		// End of user code

		return s; 
    }
    public String blocksTestExecutionRecordToHtml()
    {
		String s = "";

		// Start of user code blocksTestExecutionRecordtoHtml_init
		// End of user code

		s = s + "<label for=\"blocksTestExecutionRecord\"><strong>blocksTestExecutionRecord</strong>: </LABEL>";

		// Start of user code blocksTestExecutionRecordtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = blocksTestExecutionRecord.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code blocksTestExecutionRecordtoHtml_finalize
		// End of user code

		return s; 
    }
    public String contributorToHtml()
    {
		String s = "";

		// Start of user code contributortoHtml_init
		// End of user code

		s = s + "<label for=\"contributor\"><strong>contributor</strong>: </LABEL>";

		// Start of user code contributortoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Person> itr = contributor.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code contributortoHtml_finalize
		// End of user code

		return s; 
    }
    public String creatorToHtml()
    {
		String s = "";

		// Start of user code creatortoHtml_init
		// End of user code

		s = s + "<label for=\"creator\"><strong>creator</strong>: </LABEL>";

		// Start of user code creatortoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Person> itr = creator.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code creatortoHtml_finalize
		// End of user code

		return s; 
    }
    public String dctermsTypeToHtml()
    {
		String s = "";

		// Start of user code dctermsTypetoHtml_init
		// End of user code

		s = s + "<label for=\"type\"><strong>type</strong>: </LABEL>";

		// Start of user code dctermsTypetoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Type> itr = dctermsType.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code dctermsTypetoHtml_finalize
		// End of user code

		return s; 
    }
    public String implementsRequirementToHtml()
    {
		String s = "";

		// Start of user code implementsRequirementtoHtml_init
		// End of user code

		s = s + "<label for=\"implementsRequirement\"><strong>implementsRequirement</strong>: </LABEL>";

		// Start of user code implementsRequirementtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = implementsRequirement.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code implementsRequirementtoHtml_finalize
		// End of user code

		return s; 
    }
    public String relatedChangeRequestToHtml()
    {
		String s = "";

		// Start of user code relatedChangeRequesttoHtml_init
		// End of user code

		s = s + "<label for=\"relatedChangeRequest\"><strong>relatedChangeRequest</strong>: </LABEL>";

		// Start of user code relatedChangeRequesttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = relatedChangeRequest.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code relatedChangeRequesttoHtml_finalize
		// End of user code

		return s; 
    }
    public String relatedTestCaseToHtml()
    {
		String s = "";

		// Start of user code relatedTestCasetoHtml_init
		// End of user code

		s = s + "<label for=\"relatedTestCase\"><strong>relatedTestCase</strong>: </LABEL>";

		// Start of user code relatedTestCasetoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = relatedTestCase.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code relatedTestCasetoHtml_finalize
		// End of user code

		return s; 
    }
    public String relatedTestExecutionRecordToHtml()
    {
		String s = "";

		// Start of user code relatedTestExecutionRecordtoHtml_init
		// End of user code

		s = s + "<label for=\"relatedTestExecutionRecord\"><strong>relatedTestExecutionRecord</strong>: </LABEL>";

		// Start of user code relatedTestExecutionRecordtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = relatedTestExecutionRecord.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code relatedTestExecutionRecordtoHtml_finalize
		// End of user code

		return s; 
    }
    public String relatedTestPlanToHtml()
    {
		String s = "";

		// Start of user code relatedTestPlantoHtml_init
		// End of user code

		s = s + "<label for=\"relatedTestPlan\"><strong>relatedTestPlan</strong>: </LABEL>";

		// Start of user code relatedTestPlantoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = relatedTestPlan.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code relatedTestPlantoHtml_finalize
		// End of user code

		return s; 
    }
    public String relatedTestScriptToHtml()
    {
		String s = "";

		// Start of user code relatedTestScripttoHtml_init
		// End of user code

		s = s + "<label for=\"relatedTestScript\"><strong>relatedTestScript</strong>: </LABEL>";

		// Start of user code relatedTestScripttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = relatedTestScript.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code relatedTestScripttoHtml_finalize
		// End of user code

		return s; 
    }
    public String subjectToHtml()
    {
		String s = "";

		// Start of user code subjecttoHtml_init
		// End of user code

		s = s + "<label for=\"subject\"><strong>subject</strong>: </LABEL>";

		// Start of user code subjecttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<String> itr = subject.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
					s= s + itr.next().toString();
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code subjecttoHtml_finalize
		// End of user code

		return s; 
    }
    public String testedByTestCaseToHtml()
    {
		String s = "";

		// Start of user code testedByTestCasetoHtml_init
		// End of user code

		s = s + "<label for=\"testedByTestCase\"><strong>testedByTestCase</strong>: </LABEL>";

		// Start of user code testedByTestCasetoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = testedByTestCase.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code testedByTestCasetoHtml_finalize
		// End of user code

		return s; 
    }
    public String tracksChangeSetToHtml()
    {
		String s = "";

		// Start of user code tracksChangeSettoHtml_init
		// End of user code

		s = s + "<label for=\"tracksChangeSet\"><strong>tracksChangeSet</strong>: </LABEL>";

		// Start of user code tracksChangeSettoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = tracksChangeSet.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code tracksChangeSettoHtml_finalize
		// End of user code

		return s; 
    }
    public String tracksRequirementToHtml()
    {
		String s = "";

		// Start of user code tracksRequirementtoHtml_init
		// End of user code

		s = s + "<label for=\"tracksRequirement\"><strong>tracksRequirement</strong>: </LABEL>";

		// Start of user code tracksRequirementtoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = tracksRequirement.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code tracksRequirementtoHtml_finalize
		// End of user code

		return s; 
    }
    public String rdfTypeToHtml()
    {
		String s = "";

		// Start of user code rdfTypetoHtml_init
		// End of user code

		s = s + "<label for=\"type\"><strong>type</strong>: </LABEL>";

		// Start of user code rdfTypetoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<URI> itr = rdfType.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
					s= s + itr.next().toString();
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code rdfTypetoHtml_finalize
		// End of user code

		return s; 
    }
    public String approvedToHtml()
    {
		String s = "";

		// Start of user code approvedtoHtml_init
		// End of user code

		s = s + "<label for=\"approved\"><strong>approved</strong>: </LABEL>";

		// Start of user code approvedtoHtml_mid
		// End of user code

		try {
				if (approved == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + approved.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code approvedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String closedToHtml()
    {
		String s = "";

		// Start of user code closedtoHtml_init
		// End of user code

		s = s + "<label for=\"closed\"><strong>closed</strong>: </LABEL>";

		// Start of user code closedtoHtml_mid
		// End of user code

		try {
				if (closed == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + closed.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code closedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String closeDateToHtml()
    {
		String s = "";

		// Start of user code closeDatetoHtml_init
		// End of user code

		s = s + "<label for=\"closeDate\"><strong>closeDate</strong>: </LABEL>";

		// Start of user code closeDatetoHtml_mid
		// End of user code

		try {
				if (closeDate == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + closeDate.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code closeDatetoHtml_finalize
		// End of user code

		return s; 
    }
    public String createdToHtml()
    {
		String s = "";

		// Start of user code createdtoHtml_init
		// End of user code

		s = s + "<label for=\"created\"><strong>created</strong>: </LABEL>";

		// Start of user code createdtoHtml_mid
		// End of user code

		try {
				if (created == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + created.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code createdtoHtml_finalize
		// End of user code

		return s; 
    }
    public String descriptionToHtml()
    {
		String s = "";

		// Start of user code descriptiontoHtml_init
		// End of user code

		s = s + "<label for=\"description\"><strong>description</strong>: </LABEL>";

		// Start of user code descriptiontoHtml_mid
		// End of user code

		try {
				if (description == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + description.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code descriptiontoHtml_finalize
		// End of user code

		return s; 
    }
    public String discussedByToHtml()
    {
		String s = "";

		// Start of user code discussedBytoHtml_init
		// End of user code

		s = s + "<label for=\"discussedBy\"><strong>discussedBy</strong>: </LABEL>";

		// Start of user code discussedBytoHtml_mid
		// End of user code

		try {
                    if (discussedBy.getValue() == null) {
                        s = s + "<em>null</em>";             
                    }
                    else {
                        s = s + discussedBy.getValue().toString();                
                    }


	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code discussedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String fixedToHtml()
    {
		String s = "";

		// Start of user code fixedtoHtml_init
		// End of user code

		s = s + "<label for=\"fixed\"><strong>fixed</strong>: </LABEL>";

		// Start of user code fixedtoHtml_mid
		// End of user code

		try {
				if (fixed == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + fixed.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code fixedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String identifierToHtml()
    {
		String s = "";

		// Start of user code identifiertoHtml_init
		// End of user code

		s = s + "<label for=\"identifier\"><strong>identifier</strong>: </LABEL>";

		// Start of user code identifiertoHtml_mid
		// End of user code

		try {
				if (identifier == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + identifier.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code identifiertoHtml_finalize
		// End of user code

		return s; 
    }
    public String inprogressToHtml()
    {
		String s = "";

		// Start of user code inprogresstoHtml_init
		// End of user code

		s = s + "<label for=\"inprogress\"><strong>inprogress</strong>: </LABEL>";

		// Start of user code inprogresstoHtml_mid
		// End of user code

		try {
				if (inprogress == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + inprogress.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code inprogresstoHtml_finalize
		// End of user code

		return s; 
    }
    public String instanceShapeToHtml()
    {
		String s = "";

		// Start of user code instanceShapetoHtml_init
		// End of user code

		s = s + "<label for=\"instanceShape\"><strong>instanceShape</strong>: </LABEL>";

		// Start of user code instanceShapetoHtml_mid
		// End of user code

		try {
                    if (instanceShape.getValue() == null) {
                        s = s + "<em>null</em>";             
                    }
                    else {
                        s = s + instanceShape.getValue().toString();                
                    }


	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code instanceShapetoHtml_finalize
		// End of user code

		return s; 
    }
    public String modifiedToHtml()
    {
		String s = "";

		// Start of user code modifiedtoHtml_init
		// End of user code

		s = s + "<label for=\"modified\"><strong>modified</strong>: </LABEL>";

		// Start of user code modifiedtoHtml_mid
		// End of user code

		try {
				if (modified == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + modified.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code modifiedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String reviewedToHtml()
    {
		String s = "";

		// Start of user code reviewedtoHtml_init
		// End of user code

		s = s + "<label for=\"reviewed\"><strong>reviewed</strong>: </LABEL>";

		// Start of user code reviewedtoHtml_mid
		// End of user code

		try {
				if (reviewed == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + reviewed.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code reviewedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String serviceProviderToHtml()
    {
		String s = "";

		// Start of user code serviceProvidertoHtml_init
		// End of user code

		s = s + "<label for=\"serviceProvider\"><strong>serviceProvider</strong>: </LABEL>";

		// Start of user code serviceProvidertoHtml_mid
		// End of user code

		try {
				if (serviceProvider == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + serviceProvider.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code serviceProvidertoHtml_finalize
		// End of user code

		return s; 
    }
    public String shortTitleToHtml()
    {
		String s = "";

		// Start of user code shortTitletoHtml_init
		// End of user code

		s = s + "<label for=\"shortTitle\"><strong>shortTitle</strong>: </LABEL>";

		// Start of user code shortTitletoHtml_mid
		// End of user code

		try {
				if (shortTitle == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + shortTitle.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code shortTitletoHtml_finalize
		// End of user code

		return s; 
    }
    public String statusToHtml()
    {
		String s = "";

		// Start of user code statustoHtml_init
		// End of user code

		s = s + "<label for=\"status\"><strong>status</strong>: </LABEL>";

		// Start of user code statustoHtml_mid
		// End of user code

		try {
				if (status == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + status.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code statustoHtml_finalize
		// End of user code

		return s; 
    }
    public String titleToHtml()
    {
		String s = "";

		// Start of user code titletoHtml_init
		// End of user code

		s = s + "<label for=\"title\"><strong>title</strong>: </LABEL>";

		// Start of user code titletoHtml_mid
		// End of user code

		try {
				if (title == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + title.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code titletoHtml_finalize
		// End of user code

		return s; 
    }
    public String verifiedToHtml()
    {
		String s = "";

		// Start of user code verifiedtoHtml_init
		// End of user code

		s = s + "<label for=\"verified\"><strong>verified</strong>: </LABEL>";

		// Start of user code verifiedtoHtml_mid
		// End of user code

		try {
				if (verified == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + verified.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code verifiedtoHtml_finalize
		// End of user code

		return s; 
    }

}

