/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
package se.kth.md.it.bcm.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import se.kth.md.it.bcm.BugzillaAdaptorManager;
import se.kth.md.it.bcm.BugzillaAdaptorConstants;
import se.kth.md.it.bcm.servlet.ServiceProviderCatalogSingleton;
import se.kth.md.it.bcm.resources.BugzillaChangeRequest;	
import se.kth.md.it.bcm.resources.ChangeRequest;	
import se.kth.md.it.bcm.resources.Person;	
import se.kth.md.it.bcm.resources.Type;	

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

@OslcService(BugzillaAdaptorConstants.CHANGE_MANAGEMENT_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/bugzillaChangeRequests")
public class BugzillaChangeRequestService
{
	@Context private HttpServletRequest httpServletRequest;
	@Context private HttpServletResponse httpServletResponse;
	@Context private UriInfo uriInfo;

	// Start of user code class_attributes
	// End of user code
	
	// Start of user code class_methods
	// End of user code
	
    public BugzillaChangeRequestService()
    {
        super();
    }

    /**
     * RDF/XML, XML and JSON representation of a change request collection
     * 
     * TODO:  add query support
     * 
     * @param productId
     * @param where
     * @param pageString
     * @return
     * @throws IOException
     * @throws ServletException
     */
    @OslcQueryCapability
    (
        title = "Change Request Query Capability",
        label = "Change Request Catalog Query",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + BugzillaAdaptorConstants.PATH_BUGZILLACHANGEREQUEST,
        resourceTypes = {BugzillaAdaptorConstants.TYPE_BUGZILLACHANGEREQUEST},
        usages = {OslcConstants.OSLC_USAGE_DEFAULT}
    ) 
    @GET 
    
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public BugzillaChangeRequest[] queryBugzillaChangeRequests(
													@PathParam("serviceProviderId") final String serviceProviderId ,
    		                                 		@QueryParam("oslc.where") final String where,
    		                                 		@QueryParam("page") final String pageString,
													@QueryParam("limit") final String limitString) throws IOException, ServletException 
    {
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}
        
		// Start of user code queryBugzillaChangeRequests
		// End of user code

        final List<BugzillaChangeRequest> resources = BugzillaAdaptorManager.queryBugzillaChangeRequests(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new BugzillaChangeRequest [resources.size()]);
    }

    /**
     * HTML representation of change request collection
     * 
     * Forwards to changerequest_collection_html.jsp to build the html page
     * 
     * @param productId
     * @param changeRequestId
     * @param pageString
     * @return
     * @throws ServletException
     * @throws IOException
     */
	@GET
    
	@Produces({ MediaType.TEXT_HTML })
	public Response queryBugzillaChangeRequestsAsHtml(
									@PathParam("serviceProviderId") final String serviceProviderId ,
                               		@QueryParam("oslc.where") final String where,
                               		@QueryParam("page") final String pageString,
			                        @QueryParam("limit") final String limitString) throws ServletException, IOException
	{
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}

		// Start of user code queryBugzillaChangeRequestsAsHtml
		// End of user code

        final List<BugzillaChangeRequest> resources = BugzillaAdaptorManager.queryBugzillaChangeRequests(httpServletRequest, serviceProviderId, where, page, limit);
		
        if (resources!= null) {
        	httpServletRequest.setAttribute("resources", resources);
			// Start of user code queryBugzillaChangeRequestsAsHtml_setAttributes
			// End of user code

        	httpServletRequest.setAttribute("queryUri", 
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
        	if (resources.size() > limit) {
        		resources.remove(resources.size() - 1);
        		httpServletRequest.setAttribute("nextPageUri", 
        				uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
        	}
        	RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequestscollection.jsp");
        	rd.forward(httpServletRequest,httpServletResponse);
        }
		
		throw new WebApplicationException(Status.NOT_FOUND);	
	}

	/**
	 * OSLC delegated selection dialog for change requests
	 * 
	 * If called without a "terms" parameter, forwards to changerequest_selector.jsp to 
	 * build the html for the IFrame
	 * 
	 * If called with a "terms" parameter, sends a Bug search to Bugzilla and then 
	 * forwards to changerequest_filtered_json.jsp to build a JSON response
	 * 
	 * 
	 * @param terms
	 * @param productId
	 * @throws ServletException
	 * @throws IOException
	 */

    @OslcDialog
    (
         title = "Change Request Selection Dialog",
         label = "Change Request Selection Dialog",
         uri = "serviceProviders/{serviceProviderId}/bugzillaChangeRequests/selector",
         hintWidth = "525px",
         hintHeight = "325px",
         resourceTypes = {BugzillaAdaptorConstants.TYPE_BUGZILLACHANGEREQUEST},
         usages = {OslcConstants.OSLC_USAGE_DEFAULT}
    )
	@GET
	@Path("selector")
	@Consumes({ MediaType.TEXT_HTML, MediaType.WILDCARD })
	public void BugzillaChangeRequestSelector(
        @QueryParam("terms") final String terms
		, @PathParam("serviceProviderId") final String serviceProviderId
        ) throws ServletException, IOException
	{
		try {
			// Start of user code BugzillaChangeRequestSelector_init
			// End of user code

			httpServletRequest.setAttribute("selectionUri",uriInfo.getAbsolutePath().toString());
			// Start of user code BugzillaChangeRequestSelector_setAttributes
			httpServletRequest.setAttribute("bugzillaUri", BugzillaAdaptorManager.getBugzillaUri());
			// End of user code

			if (terms != null ) {
				httpServletRequest.setAttribute("terms", terms);
				final List<BugzillaChangeRequest> resources = BugzillaAdaptorManager.BugzillaChangeRequestSelector(httpServletRequest, serviceProviderId, terms);      
				if (resources!= null) {
							httpServletRequest.setAttribute("resources", resources);
							RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequestselectorresults.jsp"); 
							rd.forward(httpServletRequest, httpServletResponse);
				}
				//a empty search should return an empty list and not NULL!
				throw new WebApplicationException(Status.NOT_FOUND);	
			
			} else {
				try {	
					RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequestselector.jsp"); 
					rd.forward(httpServletRequest, httpServletResponse);
				} catch (Exception e) {
					throw new ServletException(e);
				}
			}
		} catch (Exception e) {
			throw new WebApplicationException(e);
		}
	}

	/**
	 * Create a single BugzillaChangeRequest via RDF/XML, XML or JSON POST
	 * @param productId
	 * @param changeRequest
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 */
	@OslcCreationFactory
	(
		 title = "Change Request Creation Factory",
		 label = "Change Request Creation",
		 resourceShapes = {OslcConstants.PATH_RESOURCE_SHAPES + "/" + BugzillaAdaptorConstants.PATH_BUGZILLACHANGEREQUEST},
		 resourceTypes = {BugzillaAdaptorConstants.TYPE_BUGZILLACHANGEREQUEST},
		 usages = {OslcConstants.OSLC_USAGE_DEFAULT}
	)
    @POST
    @Path("create")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public Response createBugzillaChangeRequest(
            @PathParam("serviceProviderId") final String serviceProviderId , 
            final BugzillaChangeRequest aResource
        ) throws IOException, ServletException
    {
		try {
    		BugzillaChangeRequest newResource = BugzillaAdaptorManager.createBugzillaChangeRequest(httpServletRequest, aResource, serviceProviderId);
			httpServletResponse.setHeader("ETag", BugzillaAdaptorManager.getETagFromBugzillaChangeRequest(newResource));
	        return Response.created(newResource.getAbout()).entity(aResource).build();
    	} catch (Exception e) {
    		e.printStackTrace();
    		throw new WebApplicationException(e);
    	}
    }

    /**
     * OSLC delegated creation dialog for a single change request
     * 
     * Forwards to changerequest_creator.jsp to build the html form
     * 
     * @param productId
     * @throws IOException
     * @throws ServletException
     */
    @GET
	@Path("creator")
    @Consumes({MediaType.WILDCARD})
    public void BugzillaChangeRequestCreator(
                @PathParam("serviceProviderId") final String serviceProviderId
        ) throws IOException, ServletException
    {
		// Start of user code BugzillaChangeRequestCreator
		httpServletRequest.setAttribute("bugzillaUri", BugzillaAdaptorManager.getBugzillaUri());
		httpServletRequest.setAttribute("creatorUri", uriInfo.getAbsolutePath().toString());
		// End of user code

        httpServletRequest.setAttribute("serviceProviderId", serviceProviderId);

		RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequestcreator.jsp");
		rd.forward(httpServletRequest, httpServletResponse);
    }

    /**
     * Backend creator for the OSLC delegated creation dialog. 
     * 
     * Accepts the input in FormParams and returns a small JSON response
     * 
     * @param productId
     * @param component
     * @param version
     * @param summary
     * @param op_sys
     * @param platform
     * @param description
     */
    @OslcDialog
	(
         title = "Change Request Creation Dialog",
         label = "Change Request Creation Dialog",
         uri = "serviceProviders/{serviceProviderId}/bugzillaChangeRequests/creator",
         hintWidth = "600px",
         hintHeight = "375px",
         resourceTypes = {BugzillaAdaptorConstants.TYPE_BUGZILLACHANGEREQUEST},
         usages = {OslcConstants.OSLC_USAGE_DEFAULT}
	)
    @POST
	@Path("creator")
    @Consumes({ MediaType.APPLICATION_FORM_URLENCODED})
    public void createBugzillaChangeRequest(
            @PathParam("serviceProviderId") final String serviceProviderId
        ) {
    	try {
			BugzillaChangeRequest newResource = null;
	
			BugzillaChangeRequest aResource = new BugzillaChangeRequest();
	
			String[] paramValues;
	
			paramValues = httpServletRequest.getParameterValues("product");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setProduct(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("component");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setComponent(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("version");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setVersion(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("priority");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setPriority(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("platform");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setPlatform(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("operatingSystem");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setOperatingSystem(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("affectedByDefect");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addAffectedByDefect(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("affectsPlanItem");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addAffectsPlanItem(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("affectsRequirement");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addAffectsRequirement(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("affectsTestResult");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addAffectsTestResult(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("blocksTestExecutionRecord");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addBlocksTestExecutionRecord(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("contributor");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addContributor(new Person(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("creator");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addCreator(new Person(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("type");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addDctermsType(new Type(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("implementsRequirement");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addImplementsRequirement(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("relatedChangeRequest");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRelatedChangeRequest(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("relatedTestCase");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRelatedTestCase(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("relatedTestExecutionRecord");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRelatedTestExecutionRecord(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("relatedTestPlan");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRelatedTestPlan(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("relatedTestScript");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRelatedTestScript(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("subject");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addSubject(paramValues[i]);
					}
			}			
			paramValues = httpServletRequest.getParameterValues("testedByTestCase");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addTestedByTestCase(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("tracksChangeSet");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addTracksChangeSet(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("tracksRequirement");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addTracksRequirement(new Link(new URI(paramValues[i])));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("type");
			if (paramValues != null) {
		    		for(int i=0; i<paramValues.length; i++) {
						aResource.addRdfType(new URI(paramValues[i]));
					}
			}			
			paramValues = httpServletRequest.getParameterValues("approved");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setApproved(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("closed");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setClosed(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("closeDate");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setCloseDate(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("created");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setCreated(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("description");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setDescription(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("discussedBy");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setDiscussedBy(new Link(new URI(paramValues[0])));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("fixed");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setFixed(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("identifier");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setIdentifier(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("inprogress");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setInprogress(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("instanceShape");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setInstanceShape(new Link(new URI(paramValues[0])));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("modified");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setModified(new SimpleDateFormat("M/D/y").parse(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("reviewed");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setReviewed(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("serviceProvider");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setServiceProvider(new URI(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("shortTitle");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setShortTitle(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("status");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setStatus(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("title");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setTitle(paramValues[0]);
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
			paramValues = httpServletRequest.getParameterValues("verified");
			if (paramValues != null) {
					if (paramValues.length == 1) {
						if (paramValues[0].length() != 0)
							aResource.setVerified(new Boolean(paramValues[0]));
						// else, there is an empty value for that parameter, and hence ignore since the parameter is not actually set.
					} 
				
			}			
	
			newResource = BugzillaAdaptorManager.createBugzillaChangeRequest(httpServletRequest, aResource, serviceProviderId);
			
			if (newResource != null) {
				httpServletRequest.setAttribute("newResource", newResource);
				httpServletRequest.setAttribute("newResourceUri", newResource.getAbout().toString());
		
				// Send back to the form a small JSON response
				httpServletResponse.setContentType("application/json");
				httpServletResponse.setStatus(Status.CREATED.getStatusCode());
				httpServletResponse.addHeader("Location", newResource.getAbout().toString());
				PrintWriter out = httpServletResponse.getWriter();
	
				JSONObject oslcResponse = new JSONObject();
				JSONObject newResourceJson = new JSONObject();
				newResourceJson.put("rdf:resource", newResource.getAbout().toString());
				// Start of user code OSLC Resource Label
				newResourceJson.put("oslc:label", newResource.getTitle().toString());
				// End of user code
				oslcResponse.put("oslc:results", new Object[]{newResourceJson});
	
				out.print(oslcResponse.toString());
				out.close();
			}
		} catch (Exception e) {
			e.printStackTrace();
			throw new WebApplicationException(e);
		}
	}

	/**
	 * RDF/XML, XML and JSON representation of a single change request
	 * 
	 * @param productId
	 * @param changeRequestId
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 * @throws URISyntaxException
	 */
    @GET
    @Path("{bugzillaChangeRequestId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public BugzillaChangeRequest getBugzillaChangeRequest(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("bugzillaChangeRequestId") final String bugzillaChangeRequestId
        ) throws IOException, ServletException, URISyntaxException
    {
		// Start of user code getResource_init
		// End of user code

        final BugzillaChangeRequest aBugzillaChangeRequest = BugzillaAdaptorManager.getBugzillaChangeRequest(httpServletRequest, serviceProviderId, bugzillaChangeRequestId);

        if (aBugzillaChangeRequest != null) {
			// Start of user code getBugzillaChangeRequest
			// End of user code
            return aBugzillaChangeRequest;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    
    /**
     * 
     * HTML representation for a single change request  - redirect the request directly to Bugzilla
     * 
     * @param productId
     * @param changeRequestId
     * @throws ServletException
     * @throws IOException
     * @throws URISyntaxException
     */
	@GET
    @Path("{bugzillaChangeRequestId}")
	@Produces({ MediaType.TEXT_HTML })
	public Response getBugzillaChangeRequestAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("bugzillaChangeRequestId") final String bugzillaChangeRequestId
        ) throws ServletException, IOException, URISyntaxException
	{	
		// Start of user code getBugzillaChangeRequestAsHtml_init
		// End of user code

        final BugzillaChangeRequest aBugzillaChangeRequest = BugzillaAdaptorManager.getBugzillaChangeRequest(httpServletRequest, serviceProviderId, bugzillaChangeRequestId);

        if (aBugzillaChangeRequest != null) {
        	httpServletRequest.setAttribute("aBugzillaChangeRequest", aBugzillaChangeRequest);
			// Start of user code getBugzillaChangeRequestAsHtml_setAttributes
			httpServletRequest.setAttribute("bugzillaUri", BugzillaAdaptorManager.getBugzillaUri());
			// End of user code

        	RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequest.jsp");
        	rd.forward(httpServletRequest,httpServletResponse);
		}

        throw new WebApplicationException(Status.NOT_FOUND);
	}

}
