name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 4 * * 4" # catch SNAPSHOT breaking changes
  workflow_dispatch:

jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install newman
        run: npm install -g newman 
      - name: 'Build :: Bugzilla adaptor'
        run: |
          mvn -B clean verify --file adaptor-bugzilla/pom.xml
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./adaptor-bugzilla/docker-compose.yml"
      - name: Run Postman tests
        run: |
          sleep 30
          newman run ./test/Bugzilla.postman_collection.json
