name: Maven CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 4 * * 4" # catch SNAPSHOT breaking changes
  workflow_dispatch:

jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 'Build :: Bugzilla adaptor'
        run: |
          mvn -B clean verify --file adaptor-bugzilla/pom.xml
